version: '3.8'

services:
  web:
    container_name: web
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.docker
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=people_depot
      - POSTGRES_PASSWORD=people_depot
      - POSTGRES_DB=people_depot_dev
    ports:
      - 5432:5432
  mkdocs:
    container_name: mkdocs
    image: hackforlaops/mkdocs:latest
    command: mkdocs serve --dev-addr 0.0.0.0:8000
    ports:
      - 8005:8000
    volumes:
      - .:/app

volumes:
  postgres_data:
