name: Create card for new issues
on:
  issues:
    types: [opened]
jobs:
  createCard:
    runs-on: ubuntu-latest
    steps:
      - name: Create or Update Project Card
        uses: peter-evans/create-or-update-project-card@v2
        with:
          token: ${{ secrets.PAT }}
          project-name: "PD: Project Board"
          project-location: fyliu
          column-name: New Issue Review
